name: "Continuous Integration"

on:
  push:
  pull_request:
    branches: [main]

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coding-standards:
    name: "Coding standards"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.3"
          coverage: "none"

      - name: "Install dependencies (Composer)"
        uses: "ramsey/composer-install@v3"
        with:
          working-directory: ./www

      - name: "Check syntax (php-parallel-lint)"
        run: "./vendor/bin/parallel-lint src cli.php server.php --colors"
        working-directory: ./www

      - name: "Check coding standards (PHP_CodeSniffer)"
        run: "./vendor/bin/phpcs --colors"
        working-directory: ./www

  static-analysis:
    name: "Static analysis"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.3"
          coverage: "none"

      - name: "Install dependencies (Composer)"
        uses: "ramsey/composer-install@v3"
        with:
          working-directory: ./www

      - name: "Statically analyze code (PHPStan)"
        run: "./vendor/bin/phpstan --ansi"
        working-directory: ./www
